// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCoBubl7VpDmwFm6RkBC1jiFJX-3o6NMA',
    appId: '1:385744272438:web:337ba32ffd62fbb721ac97',
    messagingSenderId: '385744272438',
    projectId: 'yummy-4dacd',
    authDomain: 'yummy-4dacd.firebaseapp.com',
    storageBucket: 'yummy-4dacd.firebasestorage.app',
    measurementId: 'G-FNH3HMMY0W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhAbXe8yHfUr3rigsPVxPa9mP_IhabZkQ',
    appId: '1:385744272438:android:1f3db2ff89e7e97221ac97',
    messagingSenderId: '385744272438',
    projectId: 'yummy-4dacd',
    storageBucket: 'yummy-4dacd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBOLMHzi7--tuRp7UgZhYI8BUrzdWuWyk',
    appId: '1:385744272438:ios:c2592046dfce570c21ac97',
    messagingSenderId: '385744272438',
    projectId: 'yummy-4dacd',
    storageBucket: 'yummy-4dacd.firebasestorage.app',
    iosBundleId: 'com.example.finalDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBOLMHzi7--tuRp7UgZhYI8BUrzdWuWyk',
    appId: '1:385744272438:ios:c2592046dfce570c21ac97',
    messagingSenderId: '385744272438',
    projectId: 'yummy-4dacd',
    storageBucket: 'yummy-4dacd.firebasestorage.app',
    iosBundleId: 'com.example.finalDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCoBubl7VpDmwFm6RkBC1jiFJX-3o6NMA',
    appId: '1:385744272438:web:4810ded5eeeb49e421ac97',
    messagingSenderId: '385744272438',
    projectId: 'yummy-4dacd',
    authDomain: 'yummy-4dacd.firebaseapp.com',
    storageBucket: 'yummy-4dacd.firebasestorage.app',
    measurementId: 'G-WT25T15GKS',
  );
}
